### ISSUE TITLE
error occur with message "download nhctl error" 

### ISSUE THREAD

**Issue by 258409205** [nocalhost/nocalhost#1003]
![image](https://user-images.githubusercontent.com/87800864/135815170-8f1b7ac5-d3a1-48d4-b305-31fa073aed2e.png)

**What happened**:
error windows above appear

**What you expected to happen**:
work nornal

**How to reproduce it (as minimally and precisely as possible)**:
1. goland with no nocalost installed
2. from the plugin entry, install nocalhost
3. restart golang
4. on the start golang, you will see the error window 

**Anything else we need to know?**:

**Environment**:
GoLand 2021.2.2
Build #GO-212.5080.74, built on August 31, 2021

Runtime version: 11.0.11+9-b1504.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2022M
Cores: 8
Registry: suggest.all.run.configurations.from.context=true, ide.completion.variant.limit=500, go.run.processes.with.pty=false
Non-Bundled Plugins:  dev.nocalhost.nocalhost-intellij-plugin (0.5.9-212)

**Comment by ovaldi** [comment]
@258409205  It seems that there is a problem with your JVM’s set of trusted root certificates. We will fix it asap, and for now, you can try [this solution](https://stackoverflow.com/questions/21076179).
