### ISSUE TITLE
IDEA can not open Remote terminal

### ISSUE THREAD

**Issue by ThinkPeace** [nocalhost/nocalhost#1004]
i had connect k8s clusters, but when select [open Remote Terminal] Errors occurs:

Error occurs while loading service status
: Error while create default application: Application default.application - namespace default is installing

**Comment by ThinkPeace** [comment]
> Please leave your email address and we will contact you directly

can not accept my WeChat apply, please.

**Comment by wencaiwulue** [comment]
we already fixed this bug, please use latest version and try again
