### ISSUE TITLE
website documents' pictures can be zoomed in

### ISSUE THREAD

**Issue by Pancongwen** [nocalhost/nocalhost#102]
![image](https://user-images.githubusercontent.com/25834392/103848233-de726c00-50dc-11eb-90a5-4053c123506e.png)

**What would you like to be added**:
When I read the website documents( like [this](https://nocalhost.dev/zh/Concepts/devmode/)), the characters on pictures are so small to read. I need to right click the picture and open it in a new tab. If it is possible to zoom in pictures with just one left click?
**Why is this needed**:
People who are interested in this project can read it more convenient.

**Comment by fatjyc** [comment]
We will support later

**Comment by fatjyc** [comment]
@lyzhang1999 We have supported it!
