### ISSUE TITLE
Remote Debug is beening in Waiting pod to start...

### ISSUE THREAD

**Issue by edewofenwen** [nocalhost/nocalhost#1068]
我的开发工具是IntelliJ Idea，使用了nocalhost来调试远程k8s上的应用，点击了Remote Debug以后，控制台输出日志，显示一直处于Waiting pod to start...，Dev Config是参照文档中配置的，配置是
![image](https://user-images.githubusercontent.com/52063999/139220023-737eaf11-628a-4378-95dd-27ac293fa3b1.png)
。
debug.sh配置是
![image](https://user-images.githubusercontent.com/52063999/139220086-9b4ede3f-6f30-418f-b6dc-990e56137fef.png)
。
控制台日志是
![image](https://user-images.githubusercontent.com/52063999/139218315-c5d2edf4-517a-49d4-90a9-b7e580d04625.png)
这是什么问题呢？

**Comment by anurnomeru** [comment]
已经确定是集群无法拉取公网镜像导致，关闭此问题
