### ISSUE TITLE
why i always meet problem of "Daemon responses empty data to GetDaemonServerInfo"

### ISSUE THREAD

**Issue by RiversLee** [nocalhost/nocalhost#1081]
The problem is "Daemon responses empty data to GetDaemonServerInfo", so the nocalhost is show the cluster is unable to connect,how to solve this problem? any idea

**Comment by wencaiwulue** [comment]
you can use command: ～/.nh/bin/nhctl daemon restart, to restart daemon process, and just wait a minute because daemon will rebuild cache so it might be a little slow

**Comment by wencaiwulue** [comment]
If you still have problem，you can left you wechat id here, we will invite you to a nocalhost support group to solve this problem

**Comment by luodianhanxuan** [comment]
我也遇到同样的问题，微信：luodianhanxuan
