### ISSUE TITLE
nocalhost can not be installed successfully on k3s

### ISSUE THREAD

**Issue by Pancongwen** [nocalhost/nocalhost#110]
**What happened**:
I use a k3s cluster and want to install nocalhost. It doesn't work with nocalhost-api `CrashLoopBackOff`.

----
The output of `kubectl get pod -nnocalhost -owide`:
```
NAME                             READY   STATUS             RESTARTS   AGE   IP           NODE              NOMINATED NODE   READINESS GATES
svclb-nocalhost-web-7nkvh        1/1     Running            0          73s   10.42.1.9    node-ccf0ed90     <none>           <none>
svclb-nocalhost-web-fqms9        1/1     Running            0          73s   10.42.0.16   master-d39b1dd5   <none>           <none>
svclb-nocalhost-web-77849        1/1     Running            0          73s   10.42.2.7    node-2ffe5da9     <none>           <none>
nocalhost-web-6f8f65d48f-xvzwt   1/1     Running            0          73s   10.42.2.8    node-2ffe5da9     <none>           <none>
nocalhost-api-7bdd895d99-tbthc   0/1     CrashLoopBackOff   3          73s   10.42.1.8    node-ccf0ed90     <none>           <none>
```
----
The log of nocalhost-api pod:
```
# kubectl logs -f -nnocalhost nocalhost-api-7bdd895d99-tbthc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb7d260]

goroutine 1 [running]:
nocalhost/pkg/nocalhost-api/pkg/log.Errorf(...)
        /opt/src/pkg/nocalhost-api/pkg/log/logger.go:121
nocalhost/internal/nocalhost-api/model.openDB(0xc000594118, 0x4, 0xc000594130, 0x4, 0xc000476460, 0x16, 0xc0005940f0, 0x9, 0xc00034fd80)
        /opt/src/internal/nocalhost-api/model/init.go:53 +0x4c0
nocalhost/internal/nocalhost-api/model.Init(0x1959b60)
        /opt/src/internal/nocalhost-api/model/init.go:34 +0x14d
nocalhost/pkg/nocalhost-api/napp.New(0xc0003cc340, 0x17)
        /opt/src/pkg/nocalhost-api/napp/app.go:62 +0x4e
main.main()
        /opt/src/cmd/nocalhost-api/nocalhost-api.go:74 +0x319
```

**What you expected to happen**:
nocalhost install successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
My k3s cluster is using containerd instand of docker.

**Environment**:
- OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`): ubuntu 18.04.5 LTS
- nhctl version (use `nchtl version` command): v0.2.1 (defe9f2f33fda0bed2eb9791450eaa2f7badc7ed)
- helm version (use `helm version` command): 
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
- kubectl version (use `kubectl version` command): 
```bash
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-23T02:22:53Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Others:
```bash
# kubectl get node
NAME              STATUS   ROLES    AGE   VERSION
node-2ffe5da9     Ready    <none>   29h   v1.16.3-k3s.2
node-ccf0ed90     Ready    <none>   29h   v1.16.3-k3s.2
master-d39b1dd5   Ready    master   29h   v1.16.3-k3s.2
```

**Comment by Code2Life** [comment]
Same issue on AWS EKS

**Comment by Code2Life** [comment]
Finally succeeded after 5 times restarts

**Comment by jack230230** [comment]
> Finally succeeded after 5 times restarts

nocalhost-api won't start until mariadb is ready. Therefore PV must be bound to ensure mariadb's startup.

**Comment by jack230230** [comment]
> **What happened**:
> I use a k3s cluster and want to install nocalhost. It doesn't work with nocalhost-api `CrashLoopBackOff`.
> 
> The output of `kubectl get pod -nnocalhost -owide`:
> 
> ```
> NAME                             READY   STATUS             RESTARTS   AGE   IP           NODE              NOMINATED NODE   READINESS GATES
> svclb-nocalhost-web-7nkvh        1/1     Running            0          73s   10.42.1.9    node-ccf0ed90     <none>           <none>
> svclb-nocalhost-web-fqms9        1/1     Running            0          73s   10.42.0.16   master-d39b1dd5   <none>           <none>
> svclb-nocalhost-web-77849        1/1     Running            0          73s   10.42.2.7    node-2ffe5da9     <none>           <none>
> nocalhost-web-6f8f65d48f-xvzwt   1/1     Running            0          73s   10.42.2.8    node-2ffe5da9     <none>           <none>
> nocalhost-api-7bdd895d99-tbthc   0/1     CrashLoopBackOff   3          73s   10.42.1.8    node-ccf0ed90     <none>           <none>
> ```
> 
> The log of nocalhost-api pod:
> 
> ```
> # kubectl logs -f -nnocalhost nocalhost-api-7bdd895d99-tbthc
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb7d260]
> 
> goroutine 1 [running]:
> nocalhost/pkg/nocalhost-api/pkg/log.Errorf(...)
>         /opt/src/pkg/nocalhost-api/pkg/log/logger.go:121
> nocalhost/internal/nocalhost-api/model.openDB(0xc000594118, 0x4, 0xc000594130, 0x4, 0xc000476460, 0x16, 0xc0005940f0, 0x9, 0xc00034fd80)
>         /opt/src/internal/nocalhost-api/model/init.go:53 +0x4c0
> nocalhost/internal/nocalhost-api/model.Init(0x1959b60)
>         /opt/src/internal/nocalhost-api/model/init.go:34 +0x14d
> nocalhost/pkg/nocalhost-api/napp.New(0xc0003cc340, 0x17)
>         /opt/src/pkg/nocalhost-api/napp/app.go:62 +0x4e
> main.main()
>         /opt/src/cmd/nocalhost-api/nocalhost-api.go:74 +0x319
> ```
> 
> **What you expected to happen**:
> nocalhost install successfully.
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> **Anything else we need to know?**:
> My k3s cluster is using containerd instand of docker.
> 
> **Environment**:
> 
> * OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`): ubuntu 18.04.5 LTS
> * nhctl version (use `nchtl version` command): v0.2.1 ([defe9f2](https://github.com/nocalhost/nocalhost/commit/defe9f2f33fda0bed2eb9791450eaa2f7badc7ed))
> * helm version (use `helm version` command):
> 
> ```
> version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
> ```
> 
> * kubectl version (use `kubectl version` command):
> 
> ```shell
> Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-23T02:22:53Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> * Others:
> 
> ```shell
> # kubectl get node
> NAME              STATUS   ROLES    AGE   VERSION
> node-2ffe5da9     Ready    <none>   29h   v1.16.3-k3s.2
> node-ccf0ed90     Ready    <none>   29h   v1.16.3-k3s.2
> master-d39b1dd5   Ready    master   29h   v1.16.3-k3s.2
> ```

Please check if the pv of mariadb is cannot be bound. If k3s cannot provide pv provisioner.please install nocalhost without pv support.

```
nhctl init -n nocalhost -t nodeport -p 7000 --force --set mariadb.primary.persistence.enabled=false
```

**Comment by anurnomeru** [comment]
Now you can successfully install noclhost in k3s by using `nhctl init -t nodeport --force` command only:

**Environment:**

 - OS: Ubuntu 20.04.1 LTS (or earlier version)
 - nhctl version: v0.2.5


![image](https://user-images.githubusercontent.com/24870621/105296634-de9e5b80-5bf4-11eb-9d1d-a6f02d73d1a6.png)

![image](https://user-images.githubusercontent.com/24870621/105296752-e65e0000-5bf4-11eb-9000-e459962558ec.png)
