### ISSUE TITLE
能不能支持下离线安装 ？can support offline installation ? 

### ISSUE THREAD

**Issue by ishallbethat** [nocalhost/nocalhost#1102]
能否支持下离线安装 ？ 因为有的公司情况是没有互联网办公，只能离线。 所以希望能够得到支持，非常感谢。

**Comment by anurnomeru** [comment]
支持的，具体方法留一下你的微信，可以发到我的邮箱 anurnomeru@163.com，后续这块步骤会整理成文档。

Yes, for the specific method, please leave your WeChat account and send it to my email anurnomeru@163.com. And the offline installation will be added to the document.

**Comment by ishallbethat** [comment]
我的微信 IamThat



| |
Mr Wu
|
|
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月22日 10:12 |
| 收件人 | ***@***.***> |
| 抄送至 | I Shall ***@***.******@***.***> |
| 主题 | Re: [nocalhost/nocalhost] 能不能支持下离线安装 ？can support offline installation ?  (Issue #1102) |

支持的，具体方法留一下你的微信，可以发到我的邮箱 ***@***.***，后续这块步骤会整理成文档。

Yes, for the specific method, please leave your WeChat account and send it to my email ***@***.*** And the offline installation will be added to the document.

**Comment by anurnomeru** [comment]
目前离线安装文档已经更新：
The offline installation documentation has been updated:

https://nocalhost.dev/docs/installation/
