### ISSUE TITLE
JAVA IDEA 使用 Remote Debug 控制台输出 乱码问题

### ISSUE THREAD

**Issue by jokerZhou** [nocalhost/nocalhost#1125]
项目使用 springboot 在 远程debug的时候Nocalhost的控制台输出是乱码采用如下yaml配置:
name: biz-module-base-v1
serviceType: deployment
containers:
    - name: container-a24er4
      dev:
        gitUrl: ""
        image: hub.fqi.com/nocalhost/java-dev:v1
        shell: ""
        workDir: ""
        storageClass: managed-nfs-storage
        resources: null
        persistentVolumeDirs:
            - path: /root/.m2
              capacity: 10Gi
        command:
            run: []
            debug:
                - cd
                - ./biz-module-base/biz-module-base-start
                - '&&'
                - mvn
                - spring-boot:run
                - -Dfile.encoding=UTF-8
                - -Dspring-boot.run.jvmArguments="-Xdebug
                - -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"
        debug:
            remoteDebugPort: 5005
        hotReload: false
        sync:
            type: sendReceive
            filePattern: []
            ignoreFilePattern: []
        env: []
        portForward: []

**Comment by wencaiwulue** [comment]
> 项目使用 springboot 在 远程debug的时候Nocalhost的控制台输出是乱码采用如下yaml配置: name: biz-module-base-v1 serviceType: deployment containers: - name: container-a24er4 dev: gitUrl: "" image: hub.fqi.com/nocalhost/java-dev:v1 shell: "" workDir: "" storageClass: managed-nfs-storage resources: null persistentVolumeDirs: - path: /root/.m2 capacity: 10Gi command: run: [] debug: - cd - ./biz-module-base/biz-module-base-start - '&&' - mvn - spring-boot:run - -Dfile.encoding=UTF-8 - -Dspring-boot.run.jvmArguments="-Xdebug - -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005" debug: remoteDebugPort: 5005 hotReload: false sync: type: sendReceive filePattern: [] ignoreFilePattern: [] env: [] portForward: []

是windows系统嘛？本地

**Comment by jokerZhou** [comment]
额 解决了 在 IDEA的启动JVM参数里添加了 -Dfile.encoding=UTF-8 就可以了

**Comment by wencaiwulue** [comment]
好耶
