### ISSUE TITLE
Java Maven 多模块下的Spring boot 项目 在远程调试的时候,其他模块引入的是Install的Jar包而不是其他模块target目录,这个问题该如何解决呢?

### ISSUE THREAD

**Issue by jokerZhou** [nocalhost/nocalhost#1127]

**Comment by anurnomeru** [comment]
有同步其他模块的源码上去吗？

**Comment by anurnomeru** [comment]
Maven 配置看看？

**Comment by jokerZhou** [comment]
我的maven目录是这样
base
   - base-api  服务暴露的API
   - base-biz   服务的业务
   - base-start 启动服务的类
  然后我在 base-start 下面使用 springboot:run 启动项目, 然后start模块引入的是 base-biz的jar包,这个jar包是使用maven install到库中的jar包 所以我在修改 base-biz 的代码时无效

**Comment by anurnomeru** [comment]
额

还是建议发一下相关 maven 配置，另外这个问题讲道理是 maven 问题？

**Comment by jokerZhou** [comment]
讲道理是maven和springboot的问题...主要考虑这个nocalhost的实际应用..

**Comment by anurnomeru** [comment]
嗯嗯 可以发一下配置，不然这个问题很难排查，光听描述也不知道具体是什么情况

**Comment by lyzhang1999** [comment]
> 讲道理是maven和springboot的问题...主要考虑这个nocalhost的实际应用..

麻烦留一个邮箱。

**Comment by lyzhang1999** [comment]
> 我的maven目录是这样 base
> 
> * base-api  服务暴露的API
> * base-biz   服务的业务
> * base-start 启动服务的类
>   然后我在 base-start 下面使用 springboot:run 启动项目, 然后start模块引入的是 base-biz的jar包,这个jar包是使用maven install到库中的jar包 所以我在修改 base-biz 的代码时无效

我理解这是由于依赖的包是编译后的 jar 包导致的，是否能够以模块的形式引入？也就是在运行的时候对源码进行重新编译。

**Comment by baklpc** [comment]
你的好了没？ 我把源码都同步上去，springboot:run 起不来

**Comment by baymax55** [comment]
target 目录是否被忽略同步到容器里面,我的可以同步过去
![image](https://user-images.githubusercontent.com/35788491/155439605-e9baf4a6-2b8f-4aef-b64f-86c3b0dc3941.png)

**Comment by wencaiwulue** [comment]
请问好了吗？
