### ISSUE TITLE
Cannot add gke cluster in nocalhost extension: no auth provider found for name gcp

### ISSUE THREAD

**Issue by riveryc** [nocalhost/nocalhost#1129]
**What happened**:
Cannot access gke cluster from VSCode

**What you expected to happen**:
Add GKE cluster as normal

**How to reproduce it (as minimally and precisely as possible)**:
Use existing GKE kubeconfig (use GCP as auth provider)

**Anything else we need to know?**:
The GKE cluster is working in "kubernetes" extension in VSCODE.
When added in nocalhost, it's showing
![image](https://user-images.githubusercontent.com/12391265/144856040-12ca5172-c7e9-416e-aa2c-de39ead9643c.png)

**Environment**:
- OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`): Macos 12.0.1 (21A559)
- nhctl version (use `nchtl version` command): not installed, probably installed by extension, but cannot find it from PATH
- helm version (use `helm version` command): (I didn't use helm chart install anything) version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
- kubectl version (use `kubectl version` command): 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3-gke.2003", GitCommit:"b6a837065c60b193d0d31a818a0d52718b3bbcd1", GitTreeState:"clean", BuildDate:"2021-10-21T21:32:02Z", GoVersion:"go1.16.6b7", Compiler:"gc", Platform:"linux/amd64"}
- Others:
VSCode: Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z (2 wks ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by wencaiwulue** [comment]
yes, we are not support third part auth provider, but we will integrate this function as soon as possible, please keep following

**Comment by wencaiwulue** [comment]
> maybe you can use command ```kubectl config view --raw```` to generate a kubeconfig, and have a try to add this kubeconfig to nocalhost plugin, let me know it's works fine or not, thank in advance

**Comment by lyzhang1999** [comment]
please create a new serviceaccount without GCP as auth provider and add to VSCode plugin.

**Comment by riveryc** [comment]
Thanks for the reply, it's working, but would be good to have native support as the serviceaccount is not secure for sharing between every developer, and it's hard to maintain or manage those credentials for them... 

Thanks!
