### ISSUE TITLE
vscode插件登陆nocalhost server报错“certificate has expired”

### ISSUE THREAD

**Issue by chenyangxueHDU** [nocalhost/nocalhost#1134]
本地port-ward可以正常登录，但是使用ingress http地址报错，浏览器可以正常显示

**Comment by yuyicai** [comment]
- ingress 是否启用了 https ？
- https 证书是否可用（浏览器登录是否有小绿锁🔒）？

**Comment by chenyangxueHDU** [comment]
去掉vscode代理就好了，感谢大家
