### ISSUE TITLE
windows vscode中文件同步问题

### ISSUE THREAD

**Issue by greatle** [nocalhost/nocalhost#1223]
1. windows10环境，vscode
2. java工程下的文件不能同步到dev container中（自己新建的工程或用bookinfo例子都不能同步）
3. 错误信息为：
![image](https://user-images.githubusercontent.com/17866905/150442631-a52ccfb6-2ad4-4906-88e6-e287d359ce75.png)
![image](https://user-images.githubusercontent.com/17866905/150442687-8a36a11d-91d8-4594-baac-ba8acc01b2c0.png)
4. 不知道哪里配置不对，能给个建议吗
ps：在vscode中能给打开对应dev container远程终端，能够在终端中执行命令
![image](https://user-images.githubusercontent.com/17866905/150443069-6a85c6f4-5394-4843-a9ce-b235e0c2521a.png)

**Comment by anurnomeru** [comment]
无法同步的问题，你可以先检查一下你正常的 kubectl port-forward 能否正常使用，排查一下是否在 Node 上安装了 socat。

**Comment by greatle** [comment]
> 无法同步的问题，你可以先检查一下你正常的 kubectl port-forward 能否正常使用，排查一下是否在 Node 上安装了 socat。

感谢！是node上socat的问题，没有安装好

**Comment by anurnomeru** [comment]
问题已经解决了？那我这边就关掉了。
