### ISSUE TITLE
Pod is manged by a controller,

### ISSUE THREAD

**Issue by Zhuer-fx** [nocalhost/nocalhost#1233]
IDEA 进入开发模式失败：Pod XXXX is manged by a controller, can not enter DevMode。需要如何处理？

**Comment by Zhuer-fx** [comment]
开发已回复：deployment 创建的 pod 需要点 deployment 进入开发

**Comment by xavier-hou** [comment]
For static pod which actually is controller by node, but not owned by any workload. How to deal with this kind of situation?
