### ISSUE TITLE
Error running 'debug': Nocalhost context is null.

### ISSUE THREAD

**Issue by shumintao** [nocalhost/nocalhost#1242]
- .nocal/config.yaml

```
            debug:
                - make
                - api
                - '&&'
                - dlv
                - --listen=:2345
                - --headless=true
                - --api-version=2
                - --accept-multiclient
                - exec
                - ./nocald
```

![Screenshot from 2022-02-13 13-37-37](https://user-images.githubusercontent.com/26895243/153740378-9a71e6a3-cfdb-4d5d-8e15-3c98e999c27d.png)

```

下午1:33	Error running 'Unnamed': Nocalhost context is null.

下午1:34	Error running 'debug': Nocalhost context is null.

下午1:34	Error running 'debug': Nocalhost context is null.

下午1:37	Error running 'debug': Nocalhost context is null.
```

**Comment by ovaldi** [comment]
Could you show me your current service?

![image](https://user-images.githubusercontent.com/4537336/153783160-23320863-ffe8-4d14-894d-75c11807824f.png)

**Comment by shumintao** [comment]
> Could you show me your current service?
> 
> ![image](https://user-images.githubusercontent.com/4537336/153783160-23320863-ffe8-4d14-894d-75c11807824f.png)

I have solved this problem, I found that the path to the project in the file must be consistent with the selected path.

**Comment by shumintao** [comment]
I have solved this problem, I found that the path to the project in the file must be consistent with the selected path.
