### ISSUE TITLE
遗留在rancher 上的 nocalhost 镜像 无法删除

### ISSUE THREAD

**Issue by xiaolong2013** [nocalhost/nocalhost#1251]
1. vscode 中 以Duplicate 模式 启动 nocalhost 插件  链接 k8s 集群 然后正常开放 (replace 模式 的话 可以 打开 nocalhost 的时候 用 reset pod 可以解决 )
    关闭vscode的时候忘记在nocalhost中点击关闭
2. 
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/4131679/155911239-f274e41d-0d2e-46af-ac61-3545d2b0ce14.png">
3. 作为使用者: (1)希望关闭vscode 的时候 能提示一下 要手动关闭 nocalhost 中开启的项目  或者可以自动关闭
                         (2) 可以下次进去nocalhost 的时候 也可以提供 删除的按钮 可以自助去删除 

ENV:
- OS : Macos 10.15.7
- nhctl:  v0.6.15
- helm version (use `helm version` command):
- kubectl version (use `kubectl version` command):Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
- vscode:1.64.2

**Comment by xinxinh2020** [comment]
重新打开 vscode 的时候是支持退出之前打开的的 Duplicate 模式的。目前并没有假定用户退出 VSCode 时就要退出开发模式，需要退出开发时可以打开 ide 插件退出即可。

**Comment by wencaiwulue** [comment]
> 1. vscode 中 以Duplicate 模式 启动 nocalhost 插件  链接 k8s 集群 然后正常开放 (replace 模式 的话 可以 打开 nocalhost 的时候 用 reset pod 可以解决 )
>    关闭vscode的时候忘记在nocalhost中点击关闭
> 
> <img alt="image" width="1240" src="https://user-images.githubusercontent.com/4131679/155911239-f274e41d-0d2e-46af-ac61-3545d2b0ce14.png">
> 
> 3. 作为使用者: (1)希望关闭vscode 的时候 能提示一下 要手动关闭 nocalhost 中开启的项目 或者可以自动关闭 (2) 可以下次进去nocalhost 的时候 也可以提供 删除的按钮 可以自助去删除
> ENV:
> 
> * OS : Macos 10.15.7
> * nhctl:  v0.6.15
> * helm version (use `helm version` command):
> * kubectl version (use `kubectl version` command):Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
> * vscode:1.64.2

你好，这里可能是由于nocalhost 进入的duplicate开发模式，残留了一个pod，会使用这个镜像，然后就无法删除这个镜像。这里可以尝试手动删除这个残留的pod。

**Comment by wencaiwulue** [comment]
> 1. vscode 中 以Duplicate 模式 启动 nocalhost 插件  链接 k8s 集群 然后正常开放 (replace 模式 的话 可以 打开 nocalhost 的时候 用 reset pod 可以解决 )
>    关闭vscode的时候忘记在nocalhost中点击关闭
> 
> <img alt="image" width="1240" src="https://user-images.githubusercontent.com/4131679/155911239-f274e41d-0d2e-46af-ac61-3545d2b0ce14.png">
> 
> 3. 作为使用者: (1)希望关闭vscode 的时候 能提示一下 要手动关闭 nocalhost 中开启的项目 或者可以自动关闭 (2) 可以下次进去nocalhost 的时候 也可以提供 删除的按钮 可以自助去删除
> ENV:
> 
> * OS : Macos 10.15.7
> * nhctl:  v0.6.15
> * helm version (use `helm version` command):
> * kubectl version (use `kubectl version` command):Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
> * vscode:1.64.2

残留的pod，讲道理是不会对再次进入开发模式有影响的，请放心使用 ：）
