### ISSUE TITLE
Failed to run go env

### ISSUE THREAD

**Issue by EthanLiu1991** [nocalhost/nocalhost#1252]
环境：win10 远程ssh 开发机
按照官方教程进行了debug配置。
点击”Remote Debug“后报错”Failed to run go env“

**Comment by yuyicai** [comment]
麻烦提供更多信息：
- nocalhost 版本
- 是否使用 WSL
- 粘贴更多报错信息

**Comment by EthanLiu1991** [comment]
nocalhost 版本:0.6.15
没有使用WSL，通过vscode 远程ssh 开发机
vscode版本：1.16.1
点击”Remote Debug“后报错”Failed to run go env“，无其他报错信息

**Comment by zhangjian10** [comment]
这个是已知问题，已修复，方便的话可以下载测试版插件使用

直接拖放下载插件至扩展中重启即可

https://nocalhost-generic.pkg.coding.net/nocalhost/plugins/nocalhost-vscode-plugin.vsix?version=dev

**Comment by EthanLiu1991** [comment]
> 这个是已知问题，已修复，方便的话可以下载测试版插件使用
> 
> 直接拖放下载插件至扩展中重启即可
> 
> https://nocalhost-generic.pkg.coding.net/nocalhost/plugins/nocalhost-vscode-plugin.vsix?version=dev

已解决，谢谢
