### ISSUE TITLE
Nhctl Command Warning 

### ISSUE THREAD

**Issue by zhuyaguang** [nocalhost/nocalhost#1253]
Your KubeConfig may illegal, please try to fix it by following the tips below: 
Please check if your cluster or kubeconfig is valid, Error: Post "https://127.0.0.1:39023/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": dial tcp 127.0.0.1:39023: connect: connection refused

**Comment by wencaiwulue** [comment]
> Your KubeConfig may illegal, please try to fix it by following the tips below: Please check if your cluster or kubeconfig is valid, Error: Post "https://127.0.0.1:39023/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": dial tcp 127.0.0.1:39023: connect: connection refused

it seems like you can't connect to your cluster, please check your network, or use kubectl to verify connection

**Comment by wencaiwulue** [comment]
please let me know if any news
