### ISSUE TITLE
A large number of zombie processes lead to "fork: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by thinkhp** [nocalhost/nocalhost#1255]
**What happened**:
use  GoLand 2021.3.3 + plugin Nocalhost 0.6.15-213
```sh
$ ps -A -ostat,ppid,pid,command|grep nhctl
Ss   11768     1 10:41上午   1:29.71 /Users/shareit/.nh/bin/nhctl daemon start
Z    13060 11768 10:42上午   0:00.00 (nhctl)
Z    13958 11768 10:44上午   0:00.00 (nhctl)
Z    14968 11768 10:46上午   0:00.00 (nhctl)
Z    16024 11768 10:48上午   0:00.00 (nhctl)
Z    16935 11768 10:50上午   0:00.00 (nhctl)
Z    17889 11768 10:52上午   0:00.00 (nhctl)
Z    18933 11768 10:54上午   0:00.00 (nhctl)
Z    19992 11768 10:56上午   0:00.00 (nhctl)
Z    20981 11768 10:58上午   0:00.00 (nhctl)
Z    21884 11768 11:00上午   0:00.00 (nhctl)
Z    22817 11768 11:02上午   0:00.00 (nhctl)
Z    23755 11768 11:04上午   0:00.00 (nhctl)
Z    24737 11768 11:06上午   0:00.00 (nhctl)
Z    25668 11768 11:08上午   0:00.00 (nhctl)
Z    27403 11768 11:10上午   0:00.00 (nhctl)
Z    28383 11768 11:12上午   0:00.00 (nhctl)
Z    29355 11768 11:14上午   0:00.00 (nhctl)
Z    30608 11768 11:16上午   0:00.00 (nhctl)
Z    31958 11768 11:18上午   0:00.00 (nhctl)
Z    32907 11768 11:20上午   0:00.00 (nhctl)
Z    33927 11768 11:22上午   0:00.00 (nhctl)
Z    35035 11768 11:24上午   0:00.00 (nhctl)
Z    36139 11768 11:26上午   0:00.00 (nhctl)
Z    37296 11768 11:28上午   0:00.00 (nhctl)
Z    38334 11768 11:30上午   0:00.00 (nhctl)
Z    39320 11768 11:32上午   0:00.00 (nhctl)
Z    40274 11768 11:34上午   0:00.00 (nhctl)
Z    41315 11768 11:36上午   0:00.00 (nhctl)
......
```

Every once in a while, a zombie process will be generated. After a long time, a large number of zombie processes will be generated, which will lead to exhaustion of system resources. For example, an error "fork: Resource temporarily unavailable" will be reported when using the terminal.

**Anything else we need to know?**:

in `~/.nh/nhctl/logs/nhctl.log` file, all nhctl zombie processes have logs like this:

```
Mar  4 11:12:16	[INFO]	Starting daemon server...	{"PID": "28383", "PPID": "11768", "VERSION": "v0.6.15", "COMMIT": "8887e8045ee5485f7adc0469354e9d9323a13698", "BRANCH": "HEAD", "ARGS": "/Users/shareit/.nh/bin/nhctl daemon start --sudo true", "APP": "daemon-server", "fn": "/Users/runner/work/nocalhost/nocalhost/internal/nhctl/daemon_server/daemon.go", "line": 64}
Mar  4 11:12:16	[FATAL]	, err: Failed to start daemon server with sudo
nocalhost/internal/nhctl/daemon_server.StartDaemon
	/Users/runner/work/nocalhost/nocalhost/internal/nhctl/daemon_server/daemon.go:71
nocalhost/cmd/nhctl/cmds.glob..func16
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/daemon_start.go:33
github.com/spf13/cobra.(*Command).execute
	/Users/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:860
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:974
github.com/spf13/cobra.(*Command).Execute
	/Users/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:902
nocalhost/cmd/nhctl/cmds.Execute
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/root.go:149
main.main
	/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/nhctl.go:13
runtime.main
	/Users/runner/hostedtoolcache/go/1.16.7/x64/src/runtime/proc.go:225
runtime.goexit
	/Users/runner/hostedtoolcache/go/1.16.7/x64/src/runtime/asm_arm64.s:1130	{"PID": "28383", "PPID": "11768", "VERSION": "v0.6.15", "COMMIT": "8887e8045ee5485f7adc0469354e9d9323a13698", "BRANCH": "HEAD", "ARGS": "/Users/shareit/.nh/bin/nhctl daemon start --sudo true", "APP": "daemon-server", "fn": "/Users/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/install.go", "line": 209}

```

**Environment**:
- OS:
  Macos 11.6 (20G165)
  MacBook Air (M1, 2020)
- nhctl version (use `nchtl version` command):
  nhctl: Nocalhost CLI
  Version: v0.6.15
  Branch: HEAD
  Git commit: 8887e8045ee5485f7adc0469354e9d9323a13698
  Built time: Wed Jan 19 02:15:09 2022
  Built OS/Arch: darwin/arm64
  Built Go version: go1.16.7
- helm version (use `helm version` command):
  version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}
- kubectl version (use `kubectl version` command):
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", 
  GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", 
  GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/arm64"}
  Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-r0-CCE20.8.1.3.B001-17.36.5",  
  GitCommit:"d61c11191a704802f93e5d86877a8fcffe208d58", GitTreeState:"clean", BuildDate:"2020-10-16T09:38:58Z", 
  GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Others:
  GoLand 2021.3.3
  Goland plugin Nocalhost 0.6.15-213

**Comment by xinxinh2020** [comment]
It seems a normal daemon  try to run a daemon with sudo privilege (it will failed due to permission denied)repeatly.
We will fix it soon :)

**Comment by thinkhp** [comment]
> It seems a normal daemon try to run a daemon with sudo privilege (it will failed due to permission denied)repeatly. We will fix it soon :)

This bug not only appears in start daemon server, syncthing may start and kill frequently

I checked the startup of syncthing (internal/nhctl/syncthing/syncthing.go:305) and found that the process number of the child process also needs to be recycled.
But I don't think it's very elegant, because: 1. If there are other kind child processes to start later, need add `go cmd.Run()` after each `cmd.Start()`; 2. We don't need to pay attention to the exit event of the child proceses, so I think it is better to add `signal.Ignore(syscall.SIGCHLD)`  to the main function

**Comment by xinxinh2020** [comment]
Adding `signal.Ignore(syscall.SIGCHLD)` seems a feasible solution. I will confirm it later~

**Comment by wencaiwulue** [comment]
we already fix it
