### ISSUE TITLE
does nocalhost support docker remote debugging?

### ISSUE THREAD

**Issue by shumintao** [nocalhost/nocalhost#1259]
**When I was using nocalhost, I sometimes wanted to debug docker. I wonder if I can debug it? 
Why should I debug docker? Because in kubeedge, when debugging the image of the edge node,
I found that the network is going through edgemesh, and the traffic will be relayed and forwarded and intercepted. 
I would like to ask if it can support docker remote debugging?
I don't like the remote debugging of ide very much**

**Comment by wencaiwulue** [comment]
请问下，你是要在 pod 中调试 docker吗，我们目前使用的调试方法就是 ide 的 remote debug。还有一种流量代理的模式，不知道适不适合？

**Comment by wencaiwulue** [comment]
> **When I was using nocalhost, I sometimes wanted to debug docker. I wonder if I can debug it? Why should I debug docker? Because in kubeedge, when debugging the image of the edge node, I found that the network is going through edgemesh, and the traffic will be relayed and forwarded and intercepted. I would like to ask if it can support docker remote debugging? I don't like the remote debugging of ide very much**

**Comment by shumintao** [comment]
感谢您的回复，我使用remote debug,可能是网络被edgemesh劫持的原因，导致文件同步不过去。
