### ISSUE TITLE
start DevMode Duplicate OK, but IDE show not in DevMode

### ISSUE THREAD

**Issue by thinkhp** [nocalhost/nocalhost#1269]
**What happened**:
some deployemntment start DevMode(Duplicate) ok, this is nocalhost console
```
[cmd] nhctl dev start default.application ***
Starting duplicate DevMode...
Mount workDir to emptyDir
[WARNING] Resources Limits: 500m cpu, 512Mi memory is less than the recommended minimum: 2 cpu, 2Gi memory. Running programs in DevContainer may fail. You can increase Resource Limits in Nocalhost Config
Creating ***(apps/v1, Kind=Deployment)
Resource(Deployment) *** created
Patching [{"op":"replace","path":"/spec/replicas","value":1}]
deployment.apps/*** patched (no change)

Now waiting dev mode to start...

Pod *** now Pending
 * Condition: ContainersNotReady, containers with unready status: [nocalhost-dev nocalhost-sidecar]
 >> Container: nocalhost-dev is Waiting, Reason: ContainerCreating
 >> Container: nocalhost-sidecar is Waiting, Reason: ContainerCreating

Pod *** now Running
 >> Container: nocalhost-dev is Running
 >> Container: nocalhost-sidecar is Running

deployment.apps/*** patched
 ✓  Dev container has been updated
Syncthing port-forward pod ***, namespace ***
Port-forward *** has been started
Need to download from following versions according to the sequence: v0.6.15, b847db74a698d36543a7908b9771b83fa0bd4f46
copyed syncthing v0.6.15 to ~/.nh/nhctl/bin/syncthing/syncthing

IgnoredPattern: 
.git
.idea
SyncedPattern: 
!**
 ✓  File sync started
```
but in IDE, show Not in DevMode and menu not have EndMode
<img width="151" alt="image" src="https://user-images.githubusercontent.com/26300404/159860099-d191d166-6563-47a3-a546-dc59cad2af61.png">
<img width="276" alt="image" src="https://user-images.githubusercontent.com/26300404/159860139-44c52a18-ac81-4f1a-bfd3-eb1df0f66e98.png">

Note: only some workload not all

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Note: only some workload not all

**Environment**:
- OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`):
  Macos 11.6 (20G165)
  MacBook Air (M1, 2020)
- nhctl version (use `nchtl version` command):
  nhctl: Nocalhost CLI
  Version: v0.6.15
  Branch: HEAD
  Git commit: https://github.com/nocalhost/nocalhost/commit/8887e8045ee5485f7adc0469354e9d9323a13698
  Built time: Wed Jan 19 02:15:09 2022
  Built OS/Arch: darwin/arm64
  Built Go version: go1.16.7
- helm version (use `helm version` command):
  version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}
- kubectl version (use `kubectl version` command):
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0",
  GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z",
  GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/arm64"}
  Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-r0-CCE20.8.1.3.B001-17.36.5",
  GitCommit:"d61c11191a704802f93e5d86877a8fcffe208d58", GitTreeState:"clean", BuildDate:"2020-10-16T09:38:58Z",
  GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Others:
  GoLand 2021.3.3
  Goland plugin Nocalhost 0.6.15-213

**Comment by thinkhp** [comment]
The problem has been located: in the IDE plugin, DevStatus is obtained through `nhctl get`

for abnormally displayed workload, `nhctl get deployment *** -n *** -a default.application -o json|jq .description.develop_status` output "NONE", expect "STARTED"

So I looked at the source code

cmd/nhctl/cmds/get.go:96
```
data, err := cli.SendGetResourceInfoCommand(
			kubeConfig, nameSpace, appName, resourceType, resourceName, label, false,
		)
```

internal/nhctl/daemon_server/daemon.go:161
```
case command.GetResourceInfo:
...
return daemon_handler.HandleGetResourceInfoRequest(cmd)
```

internal/nhctl/daemon_handler/get.go:349
```
serviceMap = getServiceProfile(ns, request.AppName, KubeConfigBytes)
```

internal/nhctl/daemon_handler/get.go:48
```
description := GetDescriptionDaemon(ns, appName, kubeconfigBytes)
```

internal/nhctl/daemon_handler/get.go:93
```
for _, svcProfile := range appProfile.SvcProfile {
    ...
   appmeta.FillingExtField(svcProfile, &meta, appName, ns, appProfile.Identifier)
   if m := devMeta[base.SvcType(svcProfile.GetType()).Alias()]; m != nil {
				delete(m, svcProfile.GetName())
			}
}
```

in func GetDescriptionDaemon, iterate through appProfile.SvcProfile, happen probably
1. check $(workload)-duplicate-$(id): developing, devMode replace, delete $(workload)-duplicate-$(id) in meta, deleted
2. check $(workload): not developing, devMode none, devStatus None
step 2 is not expected, so must check $(workload) before check $(workload)-duplicate-$(id)
if sorting before traversing appProfile.SvcProfile
```
		sort.Slice(appProfile.SvcProfile, func(i, j int) bool {
			vi := appProfile.SvcProfile[i]
			vj := appProfile.SvcProfile[j]
			return vi.Name < vj.Name
		})
```
it's OK

**Comment by xinxinh2020** [comment]
This is really a vague issue. Actually, $(workload)-duplicate-$(id) is dirty data created in some specific situations. Therefore, I think we can drop it directly in the following versions.
