### ISSUE TITLE
configmap修改问题

### ISSUE THREAD

**Issue by wswz963852** [nocalhost/nocalhost#1290]
开发模式或复制开发模式会直接继承原来的configmap/secret，请问不支持挂载别的configmap/secret吗？在开发环境会有修改configmap的需求，直接对原有的进行改动就达不到隔离的效果了。

**Comment by anurnomeru** [comment]
可以通过 patch 操作来对 Volumes/ VolumeMounts 进行操作：https://nocalhost.dev/docs/config/config-dev-container-en#patches

或者你有好的功能想法我们可以在这里讨论
