### ISSUE TITLE
[Bug] `Cluster` does not work in kind when using `Nocalhost Server`

### ISSUE THREAD

**Issue by yuyicai** [nocalhost/nocalhost#1317]
**What happened**:  
 `Cluster` does not work in `kind` when using `Nocalhost Server`, because the api server address of `kind` kubeconfig is 127.0.0.1  

**Anything else we need to know?**:
We can change the api server address to `https://kubernetes.default.svc` when we add the cluster.  
However, we cannot connect to the cluster from the nocalhost plugin because nhctl cannot connect to `https://kubernetes.default.svc`.  

We can add a parameter `extra_api_server`.  
When we get the kubeconfig from `DevSpace`, if `extra_api_server` exists, then replace the api server with `extra_api_server`

**Environment**:
- K8s create by kind

**Comment by yuyicai** [comment]
cc @anurnomeru @lyzhang1999 @xinxinh2020 @wencaiwulue

**Comment by anurnomeru** [comment]
This is very friendly for users using local clusters such as KIND
