### ISSUE TITLE
grpc error in mesh 

### ISSUE THREAD

**Issue by toheart** [nocalhost/nocalhost#1326]
**What happened**:
using mesh mode, call grpc error;
```shell
{
  "error": "14 UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: protocol error"
}
```
**What you expected to happen**:
normal using;
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`):
- nhctl version (use `nchtl version` command):
- helm version (use `helm version` command):
- kubectl version (use `kubectl version` command):
- Others:

**Comment by anurnomeru** [comment]
@wencaiwulue

**Comment by liwh1111** [comment]
我也碰到了这个问题,请问解决了吗

**Comment by wencaiwulue** [comment]
fixed by this commit https://github.com/nocalhost/nocalhost/pull/1429
