### ISSUE TITLE
[Bug] Nocalhost Server can't get kubeconfig for dev space on K8s v1.24.x

### ISSUE THREAD

**Issue by yuyicai** [nocalhost/nocalhost#1327]
K8s v1.24 has a feature `LegacyServiceAccountTokenNoAutoGeneration`, and enabled by default.  
When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#no-really-you-must-read-this-before-you-upgrade

So, nocalhost-api can't create kubeconfig for dev space. cc @anurnomeru

**Comment by anurnomeru** [comment]
So we need a mechanism to apply for tokens?  https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/

**Comment by yuyicai** [comment]
The `TokenRequest` feature reached beta on K8s v1.12, GA on v1.20 (https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/), but it is unclear that it is available in most cloud providers (like GKE, AKS, EKS, TKE etc.).   
And the token get from `TokenRequest` has a life cycle, we should set a non-expiring token, see: https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets
