### ISSUE TITLE
内网拉取nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-sidecar:sshversion失败

### ISSUE THREAD

**Issue by woodbay** [nocalhost/nocalhost#1362]
您好

我的K8S环境在内网，内网不能访问互联网，所以在内网K8S中无法拉取镜像nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-sidecar:sshversion

日志如下

 >> Container: nocalhost-sidecar is Waiting, Reason: ErrImagePull Msg: rpc error: code = Unknown desc = failed to pull and unpack image "nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-sidecar:sshversion": failed to resolve reference "nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-sidecar:sshversion": failed to do request: Head "https://nocalhost-docker.pkg.coding.net/v2/nocalhost/public/nocalhost-sidecar/manifests/sshversion": dial tcp: i/o timeout

**Comment by jack230230** [comment]
@anurnomeru 是不是又个配置可以修改这个镜像地址的？

**Comment by zhangjian10** [comment]
看看这个 
https://nocalhost.dev/docs/config/config-dev-container-en#sidecar-image-customization
