### ISSUE TITLE
Vscode安装完nocalhost插件后，nocalhost的配置界面是空白的。

### ISSUE THREAD

**Issue by weihanyao** [nocalhost/nocalhost#1366]
Vscode安装完nocalhost插件后，nocalhost的配置界面是空白的。
![image](https://user-images.githubusercontent.com/30789053/182763000-597f369e-ab94-4616-96e2-0e39acc8484d.png)

**Comment by zhangjian10** [comment]
麻烦补充下系统、vscode、插件版本号

**Comment by weihanyao** [comment]
Win10，vscode版本1.69.2 ，插件版本 0.6.18

**Comment by zhangjian10** [comment]
这边测试没有这个问题，能否看下vscode控制台有啥错误信息吗？

**Comment by zhangjian10** [comment]
@weihanyao

**Comment by weihanyao** [comment]
我现在把vscode更新到1.7后可以使用了
