### ISSUE TITLE
Cannot start sshd in sidecar container

### ISSUE THREAD

**Issue by jack230230** [nocalhost/nocalhost#1377]
**What happened**:

Sidecar container started failed.

![hIGFWfsjZV](https://user-images.githubusercontent.com/1728779/188633873-0b169107-16c7-43bb-961e-768d0ee4bef6.jpg)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

install harbor-helm (https://github.com/goharbor/harbor-helm) and try to develop harbor-core

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`): macOS 12.5.1 (21G83)
- nhctl version (use `nchtl version` command): 
- helm version (use `helm version` command):
- kubectl version (use `kubectl version` command):
- Others:

**Comment by ShiLei96** [comment]
I solved this problem by adding the following permissions to the sidecar container.


securityContext:
        runAsUser:0

**Comment by yuyicai** [comment]
The harhor core set the user as `1000`
https://github.com/goharbor/harbor-helm/blob/master/templates/core/core-dpl.yaml#L34
<img width="447" alt="image" src="https://user-images.githubusercontent.com/13033733/189293087-6a8ad268-b1e6-431b-a3dd-8caf9832a76a.png">
