### ISSUE TITLE
idea2022.3.1和2022.3.2在0.6.21插件下, start devmode/remote run debug都会造成IDEA卡死

### ISSUE THREAD

**Issue by r67yfyt** [nocalhost/nocalhost#1405]
![image](https://user-images.githubusercontent.com/40178408/217714774-882e8282-60e1-4b96-9890-572cf1540077.png)
标注出来的按钮执行都会卡死

手动执行 nhctl dev start没有问题
![image](https://user-images.githubusercontent.com/40178408/217716613-e4122552-f5dd-4bea-998e-9fa604d6e954.png)

两个电脑都试过
**电脑1**:
- IDEA version: 2022.3.1 
- OS : Windows 11
- nhctl version: 0.6.21-223
- helm version: v3.11.1
- kubectl version: v1.23.8
- k8s version: 1.23.8 

**电脑2**:
- IDEA version: 2022.3.2
- OS : Windows 10
- nhctl version: 0.6.21-223
- helm version: v3.11.1
- kubectl version: v1.23.8
- k8s version: 1.23.8

**Comment by anurnomeru** [comment]
我们将在 0.6.22 修复此问题

**Comment by jxfruit** [comment]
在Ubuntu上使用2023.1.3 ultimate版本下也会出现类似情况，但是Windows上却没问题
