### ISSUE TITLE
dev-images下最新golang版本号是多少？

### ISSUE THREAD

**Issue by Rebellioncry** [nocalhost/nocalhost#1413]
我远程进去看发现latest的golang版本也还是1.16.2，没有跟着golang的最新版本走吗？我现在需要最新版本1.20的该怎么办？

**Comment by chenshiwei-io** [comment]
我是自己修改下镜像版本 
golang:1.20
<img width="423" alt="image" src="https://user-images.githubusercontent.com/31839681/227412952-e9e5c3a7-3075-4d36-8697-f6aef9760396.png">

**Comment by Chever-John** [comment]
My approach was to reuse the dockerfile from this [project](https://github.com/nocalhost/dev-container) to create a newer image of the latest version of golang.

**Comment by tianyu-sz** [comment]
you can config your own image as you want

自己填需要的镜像就行.
