### ISSUE TITLE
Plugin 'Nocalhost' (version '0.6.29-231') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-233.11799.241

### ISSUE THREAD

**Issue by cochen-repo** [nocalhost/nocalhost#1444]
Plugin 'Nocalhost' (version '0.6.29-231') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-233.11799.241

**Comment by tianyu-sz** [comment]
You are using 2023.3 IDE， the support for it has just been released in the Jetbrains marketplace. Search and update the plugin ,you are good to go
