### ISSUE TITLE
JetBrains IDE 版本更新到了24.1，插件只支持23.1

### ISSUE THREAD

**Issue by assert6** [nocalhost/nocalhost#1452]
还有JetBrains IDE 版本更新到了24.1，插件只支持23.1

**Comment by assert6** [comment]
还有JetBrains IDEs 版本更新到了24.1, 插件只支持23.1

**Comment by tianyu-sz** [comment]
刚提交了2024.1支持。这一两天应该就更新能看到了（it will be available in 2 days)

https://github.com/nocalhost/nocalhost-intellij-plugin/releases/tag/v0.6.32

**Comment by tianyu-sz** [comment]
it's now available in the marketplace
