### ISSUE TITLE
install nocalhost ,got error 

### ISSUE THREAD

**Issue by tscswcn** [nocalhost/nocalhost#150]
**What happened**:
root@node-10-120-13-236:~# kubectl get pods
NAME                             READY   STATUS             RESTARTS   AGE
nocalhost-api-94f88f48d-z2wr6    0/1     CrashLoopBackOff   124        7h56m
nocalhost-web-6d54b86ddb-g4nf6   1/1     Running            211        23h
root@node-10-120-13-236:~# kubectl get sts
NAME                READY   AGE
nocalhost-mariadb   0/1     23h
root@node-10-120-13-236:~# kubectl  describe  pod nocalhost-api-94f88f48d-z2wr6
Name:         nocalhost-api-94f88f48d-z2wr6
Namespace:    default
Priority:     0
Node:         node-10-120-127-235/10.120.127.235
Start Time:   Fri, 15 Jan 2021 04:26:35 +0100
Labels:       app=nocalhost-api
              pod-template-hash=94f88f48d
Annotations:  cni.projectcalico.org/podIP: 192.168.56.155/32
              cni.projectcalico.org/podIPs: 192.168.56.155/32
Status:       Running
IP:           192.168.56.155
IPs:
  IP:           192.168.56.155
Controlled By:  ReplicaSet/nocalhost-api-94f88f48d
Containers:
  nocalhost-api:
    Container ID:  containerd://d72741a10e4d9e0beeef7e17fb1dd9f9c059a793331fb84b973d1adfc5524ff2
    Image:         codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-api:latest
    Image ID:      codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-api@sha256:d1207ea057cfdb2a836d1dc8a8156dd11a0f9980999ee795d406417e48a4c5bf
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      /app/nocalhost-api
      -c
      /app/config/config.yaml
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 15 Jan 2021 12:20:27 +0100
      Finished:     Fri, 15 Jan 2021 12:20:38 +0100
    Ready:          False
    Restart Count:  124
    Requests:
      cpu:        100m
      memory:     256Mi
    Liveness:     http-get http://:http/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:http/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /app/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kh7w4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      nocalhost-api-config
    Optional:  false
  default-token-kh7w4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kh7w4
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                       From     Message
  ----     ------   ----                      ----     -------
  Normal   Pulled   57m (x111 over 7h57m)     kubelet  Successfully pulled image "codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-api:latest"
  Normal   Pulling  52m (x112 over 7h57m)     kubelet  Pulling image "codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-api:latest"
  Warning  BackOff  2m32s (x2150 over 7h56m)  kubelet  Back-off restarting failed container
root@node-10-120-13-236:~# kubectl  logs  nocalhost-api-94f88f48d-z2wr6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb7cae0]

goroutine 1 [running]:
nocalhost/pkg/nocalhost-api/pkg/log.Errorf(...)
        /opt/src/pkg/nocalhost-api/pkg/log/logger.go:121
nocalhost/internal/nocalhost-api/model.openDB(0xc0004e4ae8, 0x4, 0xc0004e4b60, 0x4, 0xc00033b740, 0x16, 0xc0004e4a40, 0x9, 0xc000429d50)
        /opt/src/internal/nocalhost-api/model/init.go:53 +0x4c0
nocalhost/internal/nocalhost-api/model.Init(0x1947140)
        /opt/src/internal/nocalhost-api/model/init.go:34 +0x14d
nocalhost/pkg/nocalhost-api/napp.New(0xc0000c2340, 0x17)
        /opt/src/pkg/nocalhost-api/napp/app.go:62 +0x4e
main.main()
        /opt/src/cmd/nocalhost-api/nocalhost-api.go:73 +0x319

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`):

ubuntu 18.04
- nhctl version (use `nchtl version` command):
-
v0.2.4 

codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-web:latest

- helm version (use `helm version` command):
- kubectl version (use `kubectl version` command):
- Others:

**Comment by lyzhang1999** [comment]
It seems that the maridb can not bound pvc, And could not start. Please check you cluster has storageclass or not. If not, you can create pv manually.

**Comment by lyzhang1999** [comment]
or run command without pv support:
```
nhctl init -n nocalhost -t nodeport -p 7000 --force --set mariadb.primary.persistence.enabled=false
```

**Comment by lyzhang1999** [comment]
HI, have you solved this problem?

**Comment by honest1y** [comment]
Hello, The maridb had work successfully, but nocalhost-api's status was CrashLoopBackOff
`[root@master nocalhost]# kubectl get po | grep no
nocalhost-api-864bc44976-n9qpq       0/1     CrashLoopBackOff   6          9m44s
nocalhost-mariadb-0                  1/1     Running            0          28m
nocalhost-web-76d78bbb5d-z9v2j       0/1     CrashLoopBackOff   11         28m
`
`[root@master nocalhost]# kubectl logs -f nocalhost-api-864bc44976-n9qpq 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1085b84]

goroutine 1 [running]:
nocalhost/pkg/nocalhost-api/pkg/log.Errorf(0x26070cd, 0x37, 0xc00081e0c0, 0x2, 0x2)
	/opt/src/pkg/nocalhost-api/pkg/log/logger.go:120 +0x24
nocalhost/internal/nocalhost-api/model.openDB(0xc000616138, 0x4, 0xc000616150, 0x4, 0xc000048330, 0x16, 0xc000616110, 0x9, 0x0)
	/opt/src/internal/nocalhost-api/model/init.go:56 +0x548
nocalhost/internal/nocalhost-api/model.Init(0x0)
	/opt/src/internal/nocalhost-api/model/init.go:33 +0x149
nocalhost/pkg/nocalhost-api/napp.New(0xc0006aa4e0, 0x0)
	/opt/src/pkg/nocalhost-api/napp/app.go:61 +0x49
main.main()
	/opt/src/cmd/nocalhost-api/nocalhost-api.go:70 +0x4ba
`
