### ISSUE TITLE
error occurred when [Step 2: Install nocalhost server with helm]

### ISSUE THREAD

**Issue by jadeStoneStonger** [nocalhost/nocalhost#22]
hi,
When I do the [Step 2: Install nocalhost server with helm],
I typed as follows:
```
helm install nocalhost-server ./nocalhost/deployments/chart --kubeconfig=./cls-pc5oy0lu-config
```
it comes
```
Error: could not get Kubernetes config for context "": stat ./cls-pc5oy0lu-config: no such file or directory
```
so,where is this file [./cls-pc5oy0lu-config] ? it is only your local file?

**Comment by anurnomeru** [comment]
It does is a local file. You should replace `./cls-pc5oy0lu-config` with your kubeconfig such as `~/.kube/config`.

**Comment by jadeStoneStonger** [comment]
Got it
