### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by MOONYANYI** [nocalhost/nocalhost#223]
**What happened**:
**无法完成vscode 的 application的install, 本地已安装nhctl,config.yaml用的官网模板也已经添加到了项目根目录,集群已配置,请问还有什么需要配置的**
![image](https://user-images.githubusercontent.com/26380180/108995221-b7491b80-76d7-11eb-85f7-b38e070105c3.png)
![image](https://user-images.githubusercontent.com/26380180/108995318-de9fe880-76d7-11eb-98b2-eaaca46b6cb0.png)
![image](https://user-images.githubusercontent.com/26380180/108995571-40f8e900-76d8-11eb-9532-82eddcf73263.png)
**Environment**:
win10

**Comment by MOONYANYI** [comment]
Updating files: 100% (2755/2755), done.
Dependency config map installed
building dependency...
Error: Chart.yaml file is missing
fail to build dependency for helm app: : exit status 1
Error: uninstall: Release not loaded: dev: release: not found
Failed to install application : : exit status 1
**提示缺少Chart.yaml,该从何处获取**
![image](https://user-images.githubusercontent.com/26380180/109090149-7d1a6100-774d-11eb-8758-64be252b1a74.png)

**Comment by lyzhang1999** [comment]
`Chart.yaml` 是 Helm 包自带的内容，请检查 Helm 包是否有效。
