### ISSUE TITLE
nhctl init error

### ISSUE THREAD

**Issue by heytong** [nocalhost/nocalhost#27]
### step
  nhctl init -n nocalhost
### env
 openshift V4
### Err 1:  nocalhost-api
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb7cae0]

goroutine 1 [running]:
nocalhost/pkg/nocalhost-api/pkg/log.Errorf(...)
	/opt/src/pkg/nocalhost-api/pkg/log/logger.go:121
nocalhost/internal/nocalhost-api/model.openDB(0xc00038e508, 0x4, 0xc00038e550, 0x4, 0xc00025b420, 0x16, 0xc00038e440, 0x9, 0x3836218)
	/opt/src/internal/nocalhost-api/model/init.go:53 +0x4c0
nocalhost/internal/nocalhost-api/model.Init(0x1944920)
	/opt/src/internal/nocalhost-api/model/init.go:34 +0x14d
nocalhost/pkg/nocalhost-api/napp.New(0xc000158680, 0x17)
	/opt/src/pkg/nocalhost-api/napp/app.go:62 +0x45
main.main()
	/opt/src/cmd/nocalhost-api/nocalhost-api.go:74 +0x319
```
### Err 2: nocalhost-web
```
/usr/share/nginx/html/env.sh: line 2: can't create ./env.js: Permission denied
/usr/share/nginx/html/env.sh: line 8: can't create ./env.js: Permission denied
/usr/share/nginx/html/env.sh: line 9: can't create ./env.js: Permission denied
```

**Comment by daniel-zhang-dev** [comment]
i encounter the same problem 

> Err 1: nocalhost-api
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb7cae0]
goroutine 1 [running]:
nocalhost/pkg/nocalhost-api/pkg/log.Errorf(...)
	/opt/src/pkg/nocalhost-api/pkg/log/logger.go:121
nocalhost/internal/nocalhost-api/model.openDB(0xc000702208, 0x4, 0xc000702240, 0x4, 0xc000752540, 0x16, 0xc0007021c0, 0x9, 0x3836218)
	/opt/src/internal/nocalhost-api/model/init.go:53 +0x4c0
nocalhost/internal/nocalhost-api/model.Init(0x1944920)
	/opt/src/internal/nocalhost-api/model/init.go:34 +0x14d
nocalhost/pkg/nocalhost-api/napp.New(0xc00056c820, 0x17)
	/opt/src/pkg/nocalhost-api/napp/app.go:62 +0x45
main.main()
	/opt/src/cmd/nocalhost-api/nocalhost-api.go:74 +0x319

**Comment by wenxue202012** [comment]
You can refer to the special instructions of the second part of getting-started

https://nocalhost.dev/getting-started/

**Comment by jack230230** [comment]
For cluster without pv:

```
nhctl init -n nocalhost -t nodeport -p 7000 --force --set mariadb.primary.persistence.enabled=false
```
