### ISSUE TITLE
Install bookinfo failed and there is no reason metioned, just pending all the time util I stop the process

### ISSUE THREAD

**Issue by cassie6** [nocalhost/nocalhost#315]
When I try to use cmd to install bookinfo application as your course, the installation pendding there as following, no errors throw out until I stop the process by self.  Using vs code is the same. Did I miss some configurion? I use mini Kube locally.
The cmd I use: nhctl install bookinfo --kubeconfig ./config -u https://github.com/nocalhost/bookinfo.git
![image](https://user-images.githubusercontent.com/38715480/111905181-5bc73f00-8a85-11eb-8c2a-d9f575d8621f.png)

**Comment by lyzhang1999** [comment]
please check event of Pod, and you can get help directly by add wechat friend LiviA_ACG

**Comment by cassie6** [comment]
It's my network connection issue. I have fixed it, thanks!
