### ISSUE TITLE
Execute 'nhctl init demo -n nocalhost -t nodeport -p 7000 --force --set mariadb.primary.persistence.enabled=false',get error

### ISSUE THREAD

**Issue by DevialWarrior** [nocalhost/nocalhost#367]
I'm following the documents of Getting started to install Nocalhost ,in Step 2: Initialize the cluster and setup Nocalhost Server.
Execute 'nhctl init demo -n nocalhost -t nodeport -p 7000 --force --set mariadb.primary.persistence.enabled=false',I get error.
![image](https://user-images.githubusercontent.com/22161835/113844673-511be200-97c7-11eb-9087-be7b8f0e114d.png)

Kubernetes info:
![image](https://user-images.githubusercontent.com/22161835/113844887-8cb6ac00-97c7-11eb-8952-5e7db11224ae.png)

Helm info:
![image](https://user-images.githubusercontent.com/22161835/113845111-bcfe4a80-97c7-11eb-9983-3cf0dbfa1d7e.png)

**Comment by lyzhang1999** [comment]
unable to access github? please check you network.

**Comment by DevialWarrior** [comment]
Got it,thank you
