### ISSUE TITLE
Any plan for pycharm user?

### ISSUE THREAD

**Issue by cxgreat2014** [nocalhost/nocalhost#38]
From  a python developer's best wishes.

**Comment by jack230230** [comment]
We are working on add plugin for IntelliJ IDEs(PyCharm, IDEA, RubyMine etc).

**Comment by jack230230** [comment]
Here is the source of plugin for JetBrains.

https://github.com/nocalhost/nocalhost-intellij-plugin/tree/dev

You can try it though it is not completed yet.

**Comment by cxgreat2014** [comment]
> Here is the source of plugin for JetBrains.
> 
> https://github.com/nocalhost/nocalhost-intellij-plugin/tree/dev
> 
> You can try it though it is not completed yet.

Thanks for your work! 🎇🎆🎉🎉🎉
