### ISSUE TITLE
nocalhost default password is 

### ISSUE THREAD

**Issue by ipyker** [nocalhost/nocalhost#410]
After I installed it, I found that the default password for nocalhost's web interface could not be logged in. 
I'm using a helm installation. Profiles are default. 
helm install nocalhost-server ./nocalhost/deployments/chart

use account/password admin@admin.com/123456 ,Mail or password is incorrect

**Comment by anurnomeru** [comment]
By default, the service of nocalhost-web is cluster-ip and requires manual port-foward
You can change nocalhost-web's service type to load-balancer or nodeport
```
kubectl get service -n nocalhost --kubeconfig ~/.kube/tke
NAME                TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)        AGE
nocalhost-api       ClusterIP      172.21.255.114   <none>            8080/TCP       3d23h
nocalhost-mariadb   ClusterIP      172.21.254.172   <none>            3306/TCP       3d23h
nocalhost-web       LoadBalancer   172.21.255.129   xxx.xxx.xxx.xxx   80:32419/TCP   3d23h
```

Or you can port-foward the nocalhost-web to local manually

**Comment by lyzhang1999** [comment]
I success login with admin@admin.com/123456 step by step:

![image](https://user-images.githubusercontent.com/8142348/115002748-ae0a4d00-9ed7-11eb-9ff6-8b3829480fe6.png)
![image](https://user-images.githubusercontent.com/8142348/115002784-b95d7880-9ed7-11eb-80dd-172c14573f29.png)
![image](https://user-images.githubusercontent.com/8142348/115002811-bfebf000-9ed7-11eb-8d19-3f07b1e864d1.png)
![image](https://user-images.githubusercontent.com/8142348/115002841-c712fe00-9ed7-11eb-93b9-b3570280adea.png)

please check again.
