### ISSUE TITLE
nocalhost kubeconfig not support gcp

### ISSUE THREAD

**Issue by LuckyDogg** [nocalhost/nocalhost#469]
**What happened**: I create cluster from nocalhost web ui, then i add gcp kube config , it reported "KubeConfig parse error"

**What you expected to happen**: add gcp kubeconfig then add gcp cluster

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: 

**Environment**:
- OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`): 
- nhctl version (use `nchtl version` command):
- helm version (use `helm version` command): 
- kubectl version (use `kubectl version` command): 
- Others:

**Comment by lyzhang1999** [comment]
we will check this problem, can you leave you email address? so we can provide support directly.

**Comment by anurnomeru** [comment]
Is the network you created the web and gcp isolated?

**Comment by LuckyDogg** [comment]
thank u. my email is wilson.wang.hc@gmail.com

**Comment by LuckyDogg** [comment]
> Is the network you created the web and gcp isolated?

I don't think it is network problem. because nocalhost is deployed my gcp cluster . And my gcp cluster could be accessed in my local device.

**Comment by lyzhang1999** [comment]
the problem has been solved because of the problem with kubeconfig

**Comment by LuckyDogg** [comment]
this issue has been solved. GCP origin kubeconfig have to authorize by google account, so you need create another serviceaccount , then generate a new  kubeconfig to configure to nocalhost
