### ISSUE TITLE
sync: can sync outside project scope with mapping

### ISSUE THREAD

**Issue by elvizlai** [nocalhost/nocalhost#617]
**What would you like to be added**:
sync:
   - "../xxx-lib" to "../xxx-lib"

which works like docker volume.

**Why is this needed**:

Our go.mod has some replace outside developing dir, we need there dir synced to cluster.

**Comment by anurnomeru** [comment]
This is a very good idea, and we need to conduct a technical research, you can also try to submit a pr to provide this feature

**Comment by lyzhang1999** [comment]
would you please leave you email address? We want to get in touch with you directly
