### ISSUE TITLE
config.yaml application.services containers.dev.image and workDir not work

### ISSUE THREAD

**Issue by zlwandlily** [nocalhost/nocalhost#626]
**What happened**:
config.yaml not work
**What you expected to happen**:
config use v2
and config.yaml has image and workDir
but
![image](https://user-images.githubusercontent.com/44975693/120767539-dadcf700-c54d-11eb-851c-430b390d1718.png)

**How to reproduce it (as minimally and precisely as possible)**:
my config.yaml 
application:
  name: java
  manifestType: rawManifest
  resourcePath: ["manifest"]
  ignoredPath: []
  env: 
    - name: spring_name
      value: demo
  services:
    - name: java_service
      serviceType: deployment
      dependLabelSelector: {}
      containers:
        - name: java
          install: 
            env: 
              - name: containers_install_maven
                value: "yes"
            portForward:
              - 10080:8080
          dev:
            gitUrl: ""
            image: maven:3.8.1-jdk-8
            shell:  "/bin/sh"
            workDir: "/zhaoliwei/nocalhost-dev"
**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/44975693/120767885-37d8ad00-c54e-11eb-8792-0373dac6f12b.png)

**Environment**:
-Windows 10:
- nhctl version : v0.4.6
- helm version :"v3.6.0
- kubectl version : v1.21.0
- Others:

**Comment by lyzhang1999** [comment]
here is the problem:

![image](https://user-images.githubusercontent.com/8142348/120768708-06acac80-c54f-11eb-9c78-5fa30bd12539.png)

and please leave you email address, so we can provide support directly.

**Comment by zlwandlily** [comment]
Thinks，is working! but ，The documentation is not very detailed, and  idea plugin is not work in Windows
