### ISSUE TITLE
command not support？

### ISSUE THREAD

**Issue by zlwandlily** [nocalhost/nocalhost#641]
I haved set  config:
```bash
         command: 
            - "ls ./pom.xml && mvn spring-boot:run"
```
 I want that when i start Develop ,the service is running by it self,But, when i started, it's only :
 ```bash
 - command:
    - /bin/sh
    - -c
    - tail -f /dev/null
  ```
 how can i implement?

And can i speak Chinese?

**Comment by lyzhang1999** [comment]
进入开发之后，我们会把原来业务容器的 command 替换成新的 command，避免容器退出。如果要运行业务逻辑，请在容器里面运行 `mvn spring-boot:run` 直接在远程容器内启动你的程序。
另外可以留下你的 email 吗？这样我们可以提供直接的支持。

**Comment by zlwandlily** [comment]
> 进入开发之后，我们会把原来业务容器的 command 替换成新的 command，避免容器退出。如果要运行业务逻辑，请在容器里面运行 `mvn spring-boot:run` 直接在远程容器内启动你的程序。
> 另外可以留下你的 email 吗？这样我们可以提供直接的支持。

329601297@qq.com 本来想公司预研方向使用nocalhost解决容器化开发问题，但是目前来说通过验证结果，此实现对于目前的业务场景太重，可能需要通过其他方式实现，不过会持续关注此项目

**Comment by zlwandlily** [comment]
您好，此邮件表示您的来件我已收到！谢谢！
