### ISSUE TITLE
nocalhost-vscode-plugin TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zengzhengrong** [nocalhost/nocalhost#650]
vscode plugin 

version: v0.4.8

![image](https://user-images.githubusercontent.com/23110784/121776952-3ba9a680-cbc2-11eb-94e2-8c668d11de25.png)

**Comment by zenoTsai** [comment]
@zengzhengrong thank you for your feedback, we will fix it in the next version, which should not affect the use

**Comment by zenoTsai** [comment]
Fixed it
