### ISSUE TITLE
[VSCode] Repeat  define yaml object when click config 

### ISSUE THREAD

**Issue by zengzhengrong** [nocalhost/nocalhost#673]
nocalhost-vscode-plugin vserison : 0.4.10

![image](https://user-images.githubusercontent.com/23110784/122670017-6dd68c00-d1f2-11eb-948a-c35caa0f6d67.png)

save error

![image](https://user-images.githubusercontent.com/23110784/122670054-8fd00e80-d1f2-11eb-83f6-50d181092c06.png)

**Comment by anurnomeru** [comment]
Oooooops, This is a bug! We will fix it as soon as possible, or you can propose a PR to fix it

**Comment by lyzhang1999** [comment]
> Oooooops, This is a bug! We will fix it as soon as possible, or you can propose a PR to fix it

I can't reproduce the problem.

![image](https://user-images.githubusercontent.com/8142348/122706402-78dcfb00-d28a-11eb-9055-82f39e40995b.png)
