### ISSUE TITLE
安装初始化一直报错，文档太小学生了吧 很多顺序都有错误，能否提供完整顺序逻辑的文档放到官网

### ISSUE THREAD

**Issue by long0419** [nocalhost/nocalhost#707]
![image](https://user-images.githubusercontent.com/1064859/124534909-cab78080-de47-11eb-8dfb-33a3af41bd10.png)

**Comment by anurnomeru** [comment]
请问看的那篇（些）文档呢？能否留下邮箱之类的联系方式，来提供一些建议帮助我们进行文档的改善？

另外 nocalhost server 并不是一定要部署，nocalhost 最小化支持仅 IDE 插件即可使用

**Comment by long0419** [comment]
> 请问看的那篇（些）文档呢？能否留下邮箱之类的联系方式，来提供一些建议帮助我们进行文档的改善？
> 
> 另外 nocalhost server 并不是一定要部署，nocalhost 最小化支持仅 IDE 插件即可使用

![image](https://user-images.githubusercontent.com/1064859/124535870-7ca37c80-de49-11eb-9147-fbc8a29ac7d4.png)

这里的kubeconfig 是指服务器的吗？

**Comment by neaped** [comment]
@long0419 这里的 kubeconfig 指的是你需要部署的 k8s 集群的 kubeconfig，比如说你要部署到远端 k8s 集群，那么这里的 kubeconfig 就是远端 k8s 集群的 kubeconfig。你可以将目标 k8s 集群的 kubeconfig 先保存在本地，再使用命令安装。

另外，文档正在改善中，如有任何问题，可以留下联系方式，我们可以直接提供支持

**Comment by neaped** [comment]
文档结构已经更改，如果在文档方面有任何问题，欢迎重新提交问题。

**Comment by zhangalex** [comment]
@long0419   你言语还是该温和些，这是免费的东西。
