### ISSUE TITLE
why windows defender keeping alert ?

### ISSUE THREAD

**Issue by zhu733756** [nocalhost/nocalhost#721]
**What happened**:
See the picture:

![image](https://user-images.githubusercontent.com/38685176/125051515-9a851180-e0d5-11eb-9b64-823ae23d7ff7.png)

Whether the windows defender let it go or not, it would always keep alerts.

![image](https://user-images.githubusercontent.com/38685176/125054212-8d1d5680-e0d8-11eb-91f8-b580a3ecf384.png)

**Environment**:
- OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`): Windows 10
- nhctl version (use `nchtl version` command): maybe install by vscode?
- helm version (use `helm version` command): not yet
- kubectl version (use `kubectl version` command): cannot connect it.
- Others:

**Comment by lyzhang1999** [comment]
got it, we will fix it next week. Please leave your e-mail address, we will contact you directly.

**Comment by zhu733756** [comment]
> got it, we will fix it next week. Please leave your e-mail address, we will contact you directly.

Thanks. Pls email to 1079333812@qq.com or just communicate with me here.

**Comment by lyzhang1999** [comment]
this problem has been solved in release v0.4.17, please upgrade IDE plugin.
