### ISSUE TITLE
Does it support IDE debug

### ISSUE THREAD

**Issue by mouuii** [nocalhost/nocalhost#792]

**Comment by anurnomeru** [comment]
Can you describe your issue with more detail?

**Comment by lyzhang1999** [comment]
Yes, debug config example: https://github.com/lyzhang1999/zadig/blob/main/.nocalhost/config.yaml
now we support Goland and IDEA for v0.4.18, and will support PyCharm and PhpStorm in v0.4.19(this week).

if you use Goland or IDEA, you can add "Nocalhost Go" or "Nocalhost Java" after you set debug config, and click "debug" icon after enter develop mode.

<img width="281" alt="截屏2021-08-02 下午2 36 07" src="https://user-images.githubusercontent.com/8142348/127814987-7f065fa4-728b-4264-b9f5-fca1f3d74319.png">

**Comment by zou2699** [comment]
@lyzhang1999 Is there a guide?

**Comment by lyzhang1999** [comment]
https://www.bilibili.com/video/BV1Fh411B7Vb?from=search&seid=7008395873990702689

**Comment by zou2699** [comment]
@lyzhang1999 按照下面所配置的，在goland中，run 是可以的，debug几乎总是失败。
```
name: gin-demo
serviceType: deployment
containers:
  - name: gin-demo
    dev:
        gitUrl: ""
        image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/golang:1.16
        shell: ""
        workDir: /home/nocalhost-dev
        storageClass: ""
        resources: null
        persistentVolumeDirs: []
        command:
            build: []
            run:
              - go
              - run
              - ./main.go
            debug:
              - dlv
              - debug
              - ./main.go
              - --listen=:2345
              - --headless=true
              - --api-version=2
              - --accept-multiclient
            hotReloadRun: []
            hotReloadDebug: []
        debug:
            remoteDebugPort: 2345
        useDevContainer: false
        sync: null
        env:
          - name: GOPROXY
            value: https://goproxy.cn
        envFrom: null
        portForward: []
```

**Comment by lyzhang1999** [comment]
方便留一个邮箱吗？

**Comment by zou2699** [comment]
zou2699@gmail.com

**Comment by von1994** [comment]
I hava met this question too. `Remote Debug` will run command `dlv debug` in remote container and set up one port map <localhost-Port>:<dlv-listenPort>. But when I use nocalhost go `Debug` function，the debugger cannot connect to localhost mapped port(always at connecting state). Actually I can `telnet localhost
 mappedPort`.
Finally I make a port map manually like `36789:6789`，and use `Go Remote` to connect to port 36789 which at localhost.
