### ISSUE TITLE
what's the [name] mean

### ISSUE THREAD

**Issue by qiushui123** [nocalhost/nocalhost#832]
i saw every cli commad has [Name] options , what's this? 
example nhctl dev associate [Name] [flags]

**Comment by anurnomeru** [comment]
Name is the application name, you can use `nhctl list` do list all application installed.
If you did not use helm or nocalhost to install application or apply manifest, you will get only 
```
NAME                 STATE                NAMESPACE            TYPE
default.application  INSTALLED            default              rawManifestLocal
```
by calling`nhctl list`

**Comment by anurnomeru** [comment]
Currently, command line experience may difficult, recommended to use nocalhost IDE plug-ins!

**Comment by qiushui123** [comment]
thank u

**Comment by qiushui123** [comment]
why 'nhctl list [NAME] [flags]' has [name] ?

**Comment by neaped** [comment]
> why 'nhctl list [NAME] [flags]' has [name] ?

This is used for single applications details, which specify the application by name. For example, you can list application's metadata by 

```bash
nhctl list foo-app --full
```

This is a bug in the documentation, which will fix in the next doc release.

**Comment by qiushui123** [comment]
thanks
