### ISSUE TITLE
On M1 Macs: Issues  Tracker with Apple Silicon / Mac M1 问题跟踪

### ISSUE THREAD

**Issue by neaped** [nocalhost/nocalhost#853]
This is a tracker for those who have issues using Nocalhost in Mac M1.  If you run into any scenarios that don’t work quite right for you, please file an issue on GitHub so we can investigate.

## Mac OS and Nocalhost

e.g. Mac OS 11.5.2, Nocalhost 0.5.1

## IDE

e.g VS Code 1.59.1 (Universal), IDEA 2021.2

## Problem Description

e.g Takes 5 minutes to load the cluster list in VS Code.  

---
记录在 Mac M1 中使用 Nocalhost 遇到的问题 。 如果您有任何问题，请告诉我们：

## Mac OS 和 Nocalhost 的版本

例如 Mac OS 11.5.2，Nocalhost 0.5.1

## 集成开发环境和其版本

例如 VS Code 1.59.1（通用）、IDEA 2021.2

## 问题描述

例如，在 VS Code 中加载集群列表需要 5 分钟。

**Comment by neaped** [comment]
Fixed: Port-forwarding issue in M1 https://github.com/nocalhost/nocalhost/issues/786

**Comment by wencaiwulue** [comment]
我们已经正式支持了M1，请放心使用
