### ISSUE TITLE
nhctl exec don't support app deployed as statefulset

### ISSUE THREAD

**Issue by von1994** [nocalhost/nocalhost#902]
**What happened**:
My app workload type is **statefulset**. I use goland and nocalhost plugin to start remote dev. When I click the button "Run"（nocalhost run config)， the comand is like "nhctl exec test --deployment test-my-operator --controller-type statefulset --command /bin/zsh --command -c --command "go run cmd/my-operator/ma
in.go" --kubeconfig ~/.nh/intellij-plugin/kubeConfigs/d9ca5ba8-5a30-4dec-a2c9-d8ba313f0218_config --namespace default "，and the return error is " deployments.apps "test-my-operator" not found"

**What you expected to happen**:
No error returned.

**How to reproduce it (as minimally and precisely as possible)**:
App workload type is statefulset and start remote dev by click "Run"(run configured as nocalhost need)

**Anything else we need to know?**:
The func _ListPodsByDeployment_ only handle deployment resource.

**Environment**:
- OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`): macOS 11.5.1 
- nhctl version (use `nchtl version` command): 0.5.1(0.5.4 is also the same)
- helm version (use `helm version` command): none
- kubectl version (use `kubectl version` command):
- Others: nocalhost plugin version 0.5.1-211
- IDE: GoLand 2021-01

**Comment by lyzhang1999** [comment]
please upgrade your Nocalhost Plugin as v0.5.4

**Comment by anurnomeru** [comment]
we will supports soon!

**Comment by wencaiwulue** [comment]
you are right, we will support this feature on next version, please keep on follow us :)

**Comment by von1994** [comment]
> you are right, we will support this feature on next version, please keep on follow us :)


Thanks for your reply! Is there a roadmap or plan date?

**Comment by neaped** [comment]
> > you are right, we will support this feature on next version, please keep on follow us :)
> 
> Thanks for your reply! Is there a roadmap or plan date?

Hi, we will release this feature within this week.

**Comment by anurnomeru** [comment]
We will release a new version in recent days, and we have a pr to fix this issue. #903

**Comment by von1994** [comment]
Version 0.5.5 has fixed this issue.
