### ISSUE TITLE
nhctl install error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by haozi23333** [nocalhost/nocalhost#91]
点小火箭的时候, 提示这个

```
Installing application: test2
cmd: nhctl install test2 -u https://github.com/haozi23333/hello-nocaltest -t rawManifest   --resource-path .manifest/templates  --kubeconfig /Users/haozi/.nh/plugin/kubeConfigs/3_2_config
Installing application...

[git clone --depth 1 https://github.com/haozi23333/hello-nocaltest /Users/haozi/.nh/nhctl/application/test2/resources]

Cloning into '/Users/haozi/.nh/nhctl/application/test2/resources'...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x23b734a]

goroutine 1 [running]:
nocalhost/internal/nhctl/app.(*Application).InitConfig(0xc00036f920, 0x0, 0x0, 0x0, 0x0, 0x0
, 0x0)
	/home/runner/work/nocalhost/nocalhost/internal/nhctl/app/application.go:229 +0x6a
nocalhost/cmd/nhctl/cmds.InstallApplication(0x7ffeefbff73e, 0x5, 0x1, 0x27cd887)
	/home/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/install.go:138 +0x117
nocalhost/cmd/nhctl/cmds.glob..func28(0x3581860, 0xc000528120, 0x1, 0x9)
	/home/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/install.go:100 +0x185
github.com/spf13/cobra.(*Command).execute(0x3581860, 0xc000528090, 0x9, 0x9, 0x3581860, 0xc000528090)
	/home/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x3582ac0, 0xc000b3ff10, 0x1, 0x1)
	/home/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/nocalhost/nocalhost/vendor/github.com/spf13/cobra/command.go:887
nocalhost/cmd/nhctl/cmds.Execute()
	/home/runner/work/nocalhost/nocalhost/cmd/nhctl/cmds/root.go:69 +0x5a
main.main()
	/home/runner/work/nocalhost/nocalhost/cmd/nhctl/nhctl.go:22 +0x25

```
system Macos 10.15.5 (19F96)

nhctl: Nocalhost CLI
    Version: v0.2.1
    Branch: HEAD
    Git commit: defe9f2f33fda0bed2eb9791450eaa2f7badc7ed
    Built time: Tue Jan  5 12:10:36 2021
    Built OS/Arch: darwin/amd64
    Built Go version: go1.15.6

helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}

 kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"ea5f00d93211b7c80247bf607cfa422ad6fb5347", GitTreeState:"clean", BuildDate:"2020-08-13T15:11:47Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by xinxinh2020** [comment]
Hi:
This problem is caused due to a incorrect config file in .nocalhost directory.
The default config defined in .nocalhost should be config.yaml instead of config :
![image](https://user-images.githubusercontent.com/13103635/103720901-625a2480-5007-11eb-8c94-50d20fbb3806.png)

You can explicitly specify the name of config when creating application in the nocalhost-web :
![image](https://user-images.githubusercontent.com/13103635/103721370-75212900-5008-11eb-8574-bb2aab558b53.png)

Or change the name of your config file in .nocalhost to config.yaml :)

**Comment by xinxinh2020** [comment]
The error information is a little confusing. We will provide more comprehensible error information and some config validation in the following iteration.

**Comment by haozi23333** [comment]
@xinxinh2020 deployment started, but No green hammer icon

**Comment by lyzhang1999** [comment]
please add Wechat friend: LiviA_ACG, and join out Wechat group.

> @xinxinh2020 deployment started, but No green hammer icon
